[WIP] [smtr] Pipeline de realocação de linhas do SPPO
prefeitura-rio/pipelines pull request #275
Opened 2022-11-21 20:33 UTC by eng-rodrigocunha

Adiciona a pipeline para incorporar realocação de linhas, realizadas pelas empresas operadoras, visando corrigir o relacionamento entre linhas e veículos. Consequentemente, impacta na identificação de viagens e no subsídio.

2022-11-23 17:48 UTC, fernandascovino commented on pipelines/rj_smtr/constants.py
> +    REALOCACAO_SPPO_TREATED_TABLE_ID = "realocacao_sppo"
```suggestion
    REALOCACAO_SPPO_TREATED_TABLE_ID = "realocacao"
```

2022-11-23 17:49 UTC, fernandascovino commented on pipelines/rj_smtr/constants.py
> +    REALOCACAO_SPPO_RAW_TABLE_ID = "realocacao"
```suggestion
    GPS_SPPO_REALOCACAO_SPPO_RAW_TABLE_ID = "realocacao"
```

2022-11-23 17:50 UTC, fernandascovino commented on pipelines/rj_smtr/constants.py
> +    REALOCACAO_SECRET_PATH = "realocacao_api"  # TODO: Criar no vault
```suggestion
    GPS_SPPO_REALOCACAO_SECRET_PATH = "sppo_realocacao_api"  # TODO: Criar no vault
```

2022-11-23 17:51 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +        table_id=constants.REALOCACAO_SPPO_RAW_TABLE_ID.value,
```suggestion
        table_id=constants.GPS_SPPO_REALOCACAO_RAW_TABLE_ID.value,
```

2022-11-23 18:53 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    # Set dbt client #
remover comentarios

2022-11-23 18:58 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    raw_status = get_raw(url_dict["url"])
@Hellcassius @eng-rodrigocunha da parar usar o dicionário aqui caso haja recaptura com `.map`?

2022-11-23 18:58 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +realocacao_sppo.schedule = every_minute_dev
trocar para 10 minutos

2022-11-23 19:00 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    # LABELS = get_current_flow_labels()
remover comentarios

2022-11-23 19:06 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/tasks.py
> +def pre_treatment_br_rj_riodejaneiro_onibus_realocacao(
remover parametro `date_range`, não é utilizado

2022-11-23 19:07 UTC, fernandascovino requested changes
- Remover comentários do novo `flow`
- Padronizar contantes para `GPS_SPPO_REALOCACAO...`
- Padronizar secret para `sppo_realocacao_api`
- Trocar schedule para 10 minutos
- Trocar retorno de `create_api_url_onibus_realocacao` para apenas `url`
- Remover parametro `date_range` do pre tratamento

2022-11-23 21:47 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    raw_status = get_raw(url_dict["url"])
@Hellcassius creio que sim, mas precisaríamos de uma estrutura de repetição para o get_raw, certo?

2022-11-25 20:09 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    # LABELS = get_current_flow_labels()
```suggestion
```

2022-11-25 20:10 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    # MODE = get_current_flow_mode(LABELS)
```suggestion
```

2022-11-25 20:12 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/constants.py
> +    REALOCACAO_SECRET_PATH = "realocacao_api"  # TODO: Criar no vault
Vault path will not change, as agreed

2022-11-25 20:12 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/tasks.py
> +    # TODO: separar os filtros num dicionario
```suggestion
```

2022-11-25 20:30 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +        prefix="GPS SPPO Realocacao Recapturas: ",
mudar para "GPS SPPO - Realocacao (RC): "

2022-11-25 20:32 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +            status=trated_status,
corrigir:`treated_status`

2022-11-30 13:24 UTC, fernandascovino approved these changes
LGTM 👍

2022-11-30 13:46 UTC, merged