Staging/apuracao subisidio sppo
prefeitura-rio/pipelines pull request #384
Opened 2023-03-20 21:38 UTC by eng-rodrigocunha

2023-04-27 14:41 UTC, fernandascovino requested changes
@eng-rodrigocunha o flow por padrão tem que ser diário e rodar em D+5. Precisa ainda:

- ativar shedule
- mudar parametrização para D+5
- arrumar pylint (ex: tem uma função get_previous_date que é importada e não é utilizada)

2023-04-27 14:49 UTC, fernandascovino commented
@gabriel-milan não tem nenhuma modificação que impacto outras pipelines, embora esteja indicando o contrário pelo bot. Fora pipelines da smtr, tem apenas:

- correção do usuário do Rodrigo
- adição de uma task na raiz

2023-05-04 01:30 UTC, eng-rodrigocunha commented
@fernandascovino 
ativar schedule ✅
mudar parametrização para D+5 ✅
arrumar pylint ✅

2023-05-04 01:33 UTC, eng-rodrigocunha commented
> @eng-rodrigocunha o flow por padrão tem que ser diário e rodar em D+5. Precisa ainda:
> 
> * ativar schedule
> * mudar parametrização para D+5
> * arrumar pylint (ex: tem uma função get_previous_date que é importada e não é utilizada)

ativar schedule ✅
mudar parametrização para D+5 ✅
arrumar pylint ✅

Fiz mais algumas alterações, como a eliminação da `get_yesterday.run()`, substituindo pela `get_previous_date.run(1)`. Inseri também o parâmetro `publish`, para executar ou não o flow `smtr_materialize_to_datario_viagem_sppo_flow`.

2023-05-09 19:38 UTC, fernandascovino approved these changes

2023-05-09 19:38 UTC, merged