Git inicial, inclusão viagem planejada e subsidio
prefeitura-rio/pipelines pull request #462
Opened 2023-06-07 16:46 UTC by LeonePCRJ

Adição dos novos flows:

"smtr_materialize_to_datario_viagem_planejada_sppo_flow"
"smtr_materialize_to_datario_subsidio_sppo_flow"

2023-06-12 19:07 UTC, eng-rodrigocunha approved these changes

2023-06-12 19:08 UTC, eng-rodrigocunha requested changes
Finalizar testes

2023-06-13 22:54 UTC, fernandascovino approved these changes

2023-06-13 23:17 UTC, eng-rodrigocunha approved these changes

2023-06-13 23:28 UTC, merged