[SMTR] Acrescenta Boris e Rodrigo como code owners da SMTR
prefeitura-rio/pipelines pull request #467
Opened 2023-07-05 15:18 UTC by borismarinho

O commit acrescenta Boris e Rodrigo como code owners da SMTR e como marcações de alerta no Discord

2023-07-05 15:30 UTC, eng-rodrigocunha requested changes

2023-07-05 15:30 UTC, eng-rodrigocunha commented on code_owners.yaml
> +        - borismarinho
Não seria `boris`?

2023-07-05 15:30 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/projeto_subsidio_sppo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Eu estou repetido. Inserir Caio.

2023-07-05 15:30 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/veiculo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Eu estou repetido. Inserir Caio.

2023-07-05 15:30 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/veiculo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Eu estou repetido. Inserir Caio.

2023-07-05 15:30 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/veiculo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Eu estou repetido. Inserir Caio.

2023-07-05 15:35 UTC, borismarinho commented on code_owners.yaml
> +        - borismarinho
Acredito que aqui seja o usuário do github, não o apelido do discord. Observe que, para o discord os usuários são "caio", "fernanda", "boris" e  "rodrigo". Já aqui são "hellcassius", "fernandascovino", "eng-rodrigocunha" e "borismarinho"

2023-07-05 15:49 UTC, borismarinho commented on pipelines/rj_smtr/projeto_subsidio_sppo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Resolvido.

2023-07-05 15:50 UTC, borismarinho commented on pipelines/rj_smtr/veiculo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Resolvido.

2023-07-05 15:50 UTC, borismarinho commented on pipelines/rj_smtr/veiculo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Resolvido.

2023-07-05 15:50 UTC, borismarinho commented on pipelines/rj_smtr/veiculo/flows.py
> +    code_owners=["rodrigo", "fernanda", "boris", "rodrigo"],
Resolvido.

2023-07-06 19:28 UTC, eng-rodrigocunha approved these changes

2023-07-06 19:37 UTC, eng-rodrigocunha requested changes
.

2023-07-06 19:38 UTC, eng-rodrigocunha approved these changes

2023-07-06 19:38 UTC, fernandascovino approved these changes

2023-07-06 19:39 UTC, merged