Staging/sms farmacia estoque
prefeitura-rio/pipelines pull request #489
Opened 2023-08-12 12:57 UTC by ThiagoTrabach

2023-08-12 13:45 UTC, ThiagoTrabach commented
@gabriel-milan me ajuda aqui? Na hora de buildar está falhando em identificar as variáveis de ambiente  da imagem com as credenciais do Vault

2023-08-14 11:17 UTC, gabriel-milan requested changes

2023-08-14 11:17 UTC, gabriel-milan commented on pipelines/rj_sms/farmacia_estoque/flows.py
> +    ]
@ThiagoTrabach o problema tá aqui.

`get_vault_secret` não é uma `Task` do Prefect, é uma função Python comum. Toda vez que você insere alguma coisa no context do `Flow` aqui (dentro do `with Flow(...)`) que não seja uma `Task`, aquilo vai ser executado e se tornar estático. Nesse caso, então, o que está acontecendo é que, em tempo de build, ele está tentando pegar o valor da variável e configurar como constante, que claramente dá problema.

Para resolver esse problema existem dois caminhos que consigo imaginar:
- Passar o secret_path como parâmetro e pegar o secret dentro da `Task` que irá utilizá-lo (geralmente é o que adotamos)
- Criar uma `Task` para pegar o secret, que vai ser essencialmente um embrulho pra essa função `get_vault_secret` (se você precisa usar o valor do secret mais uma vez, é o que eu recomendaria)

2023-08-14 11:17 UTC, gabriel-milan commented on pipelines/rj_sms/farmacia_estoque/flows.py
> +
Notei também que falta configurar o armazenamento e ambiente de execução pros `Flow`s, que vai ser igual pra todos (ver exemplo em https://github.com/prefeitura-rio/pipelines/blob/master/pipelines/utils/dump_db/flows.py#L248)

2023-09-15 18:23 UTC, closed without merging