[WIP] Cria pipeline de captura de dados de bilhetagem da Jaé
prefeitura-rio/pipelines pull request #501
Opened 2023-08-31 17:32 UTC by eng-rodrigocunha

2023-09-06 19:36 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_bilhetagem/flows.py
> +    base_params, params, url = get_bilhetagem_url(datetime_range)
Remover esquema de mapeamento de runs

2023-09-06 19:36 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_bilhetagem/flows.py
> +        error = bq_upload(
Adicionar flag de arquivo vazio: skip na task

2023-09-06 19:37 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_bilhetagem/flows.py
> +        error = bq_upload(
Mantém upload logs normal para indicar que houve captura

2023-09-06 19:37 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_bilhetagem/flows.py
> +    labels=[emd_constants.RJ_SMTR_AGENT_LABEL.value],
```suggestion
    labels=[emd_constants.RJ_SMTR_DEV_AGENT_LABEL.value],
```

2023-09-06 19:37 UTC, fernandascovino commented on pipelines/rj_smtr/br_rj_riodejaneiro_bilhetagem/flows.py
> +bilhetagem_transacao_captura.schedule = every_minute
```suggestion
bilhetagem_transacao_captura.schedule = every_minute_dev
```

2023-09-06 19:49 UTC, fernandascovino requested changes
- Simplificar código de captura (apenas get raw, pre treat, bq upload e upload logs)
- Rever nomeações de flows e tasks
- Remover código repetido (DRY)

2023-09-06 19:51 UTC, fernandascovino commented on pipelines/rj_smtr/tasks.py
> +def pre_treatment_nest_data(
```suggestion
def pre_treatment_nested_data(
```

2023-09-15 16:07 UTC, fernandascovino commented on pipelines/rj_smtr/flows.py
> +) as captura_generico:
Trocar para algo como `default_capture_flow`, para indicar que é um flow (pois vai ser importado em outros arquivos) e que é o padrão a ser usado

2023-09-15 16:07 UTC, fernandascovino commented on pipelines/rj_smtr/flows.py
> +        create_request_params_func=create_request_params_func,
Não entendi isso, por que passar uma função?

2023-09-15 19:42 UTC, pixuimpou approved these changes

2023-09-15 19:48 UTC, fernandascovino approved these changes
LGTM 🚀

2023-09-15 19:49 UTC, merged