Change default capture structure
prefeitura-rio/pipelines pull request #520
Opened 2023-09-27 17:21 UTC by pixuimpou

2023-09-29 15:05 UTC, eng-rodrigocunha requested changes

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/constants.py
> +        {"table_id": "calendar_dates", "primary_key": ["service_id"]},
@lingsv 

Verificar documentação: https://gtfs.org/schedule/reference/#calendar_datestxt

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/constants.py
> +        {"table_id": "frequencies", "primary_key": ["trip_id"]},
@lingsv 

Verificar documentação: https://gtfs.org/schedule/reference/#frequenciestxt

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/constants.py
> +        {"table_id": "shapes", "primary_key": ["shape_id"]},
@lingsv 

Verificar documentação: https://gtfs.org/schedule/reference/#shapestxt

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/constants.py
> +        {"table_id": "fare_rules", "primary_key": ["fare_id"]},
@lingsv 

Verificar documentação: https://gtfs.org/schedule/reference/#fare_rulestxt

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/constants.py
> +    GTFS_BASE_GCS_PATH = "development/br_rj_riodejaneiro_gtfs/upload"
Atualizar path

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/flows.py
> +    # save_raw_local,
Remover tasks não utilizadas

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/flows.py
> +        source_type=source_type,  # parametro de extracao, onde ficar?
Remover comentário

2023-09-29 15:05 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/tasks.py
> +            request_url = f"{constants.GTFS_BASE_GCS_PATH.value}/gtfs.zip"
Transformar gtfs.zip em constante

2023-09-29 15:18 UTC, eng-rodrigocunha requested changes

2023-09-29 15:18 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/tasks.py
> +# @task(checkpoint=False)
Remover task

2023-09-29 15:18 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/utils.py
> +    if filetype == "txt":
Inserir CSV

2023-09-29 15:18 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/utils.py
> +        local_filepath (str): Local filepath to save raw data
Atualizar docstring

2023-09-29 15:18 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/utils.py
> +        filetype (str, optional): Filetype to save raw file. Defaults to None.
Atualizar doc string

2023-09-29 15:18 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/utils.py
> +def read_raw_data(filepath: str, csv_args: dict = dict()) -> tuple[str, pd.DataFrame]:
Checar pylint `csv_args: dict = dict()`

2023-09-29 15:21 UTC, eng-rodrigocunha requested changes

2023-09-29 15:21 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/constants.py
> +    GTFS_QUADRO_CAPTURE_PARAMS = {"table_id": "quadro", "primary_key": "servico"}
Trocar `primary_key` para lista.

2023-09-29 19:59 UTC, fernandascovino commented on pipelines/utils/custom.py
> +            # on_failure=partial(
Voltar com notificacao

2023-09-29 21:29 UTC, fernandascovino commented on pipelines/rj_smtr/constants.py
> +        "principal_runs_interval_minutes": 15,
```suggestion
        "principal_runs_interval_minutes": 5,
```

2023-10-02 14:59 UTC, eng-rodrigocunha approved these changes

2023-10-02 15:12 UTC, merged