Criação do subflow de recaptura de GPS SPPO Realocação
prefeitura-rio/pipelines pull request #668
Opened 2024-04-17 18:48 UTC by vtr363

2024-04-17 19:22 UTC, pixuimpou requested changes

2024-04-17 19:22 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +        flow_name=materialize_sppo.name,
executando o subflow errado

2024-04-17 19:22 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +with Flow(
precisa ser definido antes do tratamento, para ser possivel usar ele lá

2024-04-17 19:23 UTC, pixuimpou requested changes

2024-04-17 19:23 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +            table_id=unmapped(constants.GPS_SPPO_RAW_TABLE_ID.value),
table_id errado

2024-04-17 19:23 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +            parent_table_id=unmapped(constants.GPS_SPPO_RAW_TABLE_ID.value),
table_id errado

2024-04-17 19:23 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +            table_id=unmapped(constants.GPS_SPPO_RAW_TABLE_ID.value),
table_id errado

2024-04-17 19:23 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +        table_id=constants.GPS_SPPO_RAW_TABLE_ID.value,
table_id errado

2024-04-18 15:16 UTC, pixuimpou requested changes

2024-04-18 15:16 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +        url = create_api_url_onibus_gps.map(
alterar task

2024-04-18 15:16 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +        treated_status = pre_treatment_br_rj_riodejaneiro_onibus_gps.map(
alterar task

2024-04-18 19:57 UTC, pixuimpou requested changes

2024-04-18 19:57 UTC, pixuimpou commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    errors, timestamps, previous_errors = query_logs(
Adicionar interval_minutes correto

2024-04-19 15:38 UTC, eng-rodrigocunha requested changes

2024-04-19 15:38 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +# -*- coding: utf-8 -*-
remover duplicação

2024-04-26 02:46 UTC, eng-rodrigocunha commented on pipelines/rj_smtr/br_rj_riodejaneiro_onibus_gps/flows.py
> +    )
Adicionar timestamp como parâmetro?

2024-04-26 20:14 UTC, eng-rodrigocunha approved these changes
SGTM

2024-04-26 20:15 UTC, pixuimpou approved these changes

2024-04-26 20:15 UTC, merged